on:
  workflow_call
jobs:
  test_python:
    runs-on: ubuntu-latest
    name: Test Python
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel
      - name: Install Dependencies
        run: |
          cd python
          pipenv lock -r > requirements.txt
          cat requirements.txt
          pip install -r requirements.txt
      - name: Test
        run: cd python && ./test.py
  test_mygrations:
    runs-on: ubuntu-latest
    name: Test Mygrations
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install mygrations
        run: python -m pip install --upgrade mygrations
      - name: Check
        run: |
          echo 'files_directory = "sql/"' > mygrate.conf
          wget 'https://raw.githubusercontent.com/cmancone/mygrations/master/mygrate.py'
          chmod a+x mygrate.py
          ./mygrate.py check
